- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Change instances state by tag
      ec2:
        state: running
        instance_tags:
          Name: ansible01