- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Get instance info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        ec2_region: "{{ AWS_REGION }}"
        filters: 
          instance-state-name: [ "running", "stopped", "shutting-down" ]
      register: ec2_info
    - debug:
        var: ec2_info
    - debug:
        var: ec2_info.instances[0].instance_id
