---
- name: Terminate instances
  hosts: localhost
  vars:
    instance_ids:
      - 'i-01af3a7cc8cf649cf'
      - 'i-0789183a206c03d78'
      - 'i-08ab6d64e3672cdc3'
    region: us-east-1
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: "{{ instance_ids }}"
        region: "{{ region }}"